sitio/main/urls.py
from django.urls import path
from . import views


app_name = "main"


urlpatterns = [   
    path('', views.IndexView.as_view(), name= "home"),
    path('blog/', views.BlogView.as_view(), name="blogs"),
    path('blog/<slug:slug>', views.BlogDetailView.as_view(), name="blogs"),
    path('blogaddinfo', views.BlogAddInfo.as_view(),name="blogaddinfo")
]    

sitio/miembros/urls.py
from django.urls import path
from .views import UserRegister, UserEdit, PasswordsChange
from django.contrib.auth import views as auth_views
from . import views



urlpatterns = [
    path('register/', UserRegister.as_view(), name='register'),
    path('edit_profile/', UserEdit.as_view(), name='edit_profile'),
    path('password/', PasswordsChange.as_view(template_name='registration/change-password.html')),
    path('password_success', views.password_success, name="password_success"),
]

sitio/sitio/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include 

urlpatterns = [
    path("admin/", admin.site.urls),
    path('',include('main.urls')),  
    path('miembros/', include('django.contrib.auth.urls')),
    path('miembros/', include('miembros.urls')),
]

sitio/main/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify

class Blog(models.Model):

    class Meta:
        verbose_name_plural = 'Blog Profiles'
        verbose_name = 'Blog'
        ordering = ["timestamp"]

    timestamp = models.DateTimeField(auto_now_add=True)
    author = models.CharField(max_length=200, blank=True, null=True)
    name = models.CharField(max_length=200, blank=True, null=True)
    description = models.CharField(max_length=500, blank=True, null=True)
    body = RichTextField(blank=True, null=True)
    slug = models.SlugField(null=True, blank=True)
    image = models.ImageField(blank=True, null=True, upload_to="blog")
    is_active = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name) 
        super(Blog, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return f"/blog/{self.slug}"

       
# Create your models here.

sitio/miembros/models.py
from django.db import models

"""
los models de Usuarios ya se encuentran en la parte interna del framework django.
"""

sitio/main/forms.py
from django import forms
from .models import Blog

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

      

class BlogForm(forms.ModelForm):
    author = forms.CharField(max_length=200, required=True,widget=forms.TextInput(attrs={
        'placeholder': '*author name..',
        }))
    name = forms.CharField(max_length=200, required=True,widget=forms.TextInput(attrs={
        'placeholder':'*Full name ..',
        }))
    description = forms.CharField(max_length=500,required=True,widget=forms.TextInput(attrs={
        'placeholder':'*description..',
    }))
    body = forms.CharField(max_length=1000,required=True,widget=forms.Textarea(attrs={
        'placeholder':'*body info .. ',
    }))
    image = forms.ImageField()

    class Meta:
        model = Blog
        fields = ['author','name','description','body','image']

sitio/miembros/forms.py
"""
formulario de creacion de usuarios 

"""

from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth.models import User
#from socket import fromshare
from django import forms

class SignUpForm(UserCreationForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
    
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'



"""campos del formulario corresponde a los mismos atributos pertenecientes a los User de la libreria django"""
class EditForm(UserChangeForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_login = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_superuser = forms.CharField(max_length=100, widget=forms.CheckboxInput(attrs={'class': 'form-check'}))
    is_staff = forms.CharField(max_length=100, widget=forms.CheckboxInput(attrs={'class': 'form-check'}))
    is_active = forms.CharField(max_length=100, widget=forms.CheckboxInput(attrs={'class': 'form-check'}))
    date_joined = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'last_login', 'is_superuser', 'is_staff', 'is_active', 'date_joined')
     


""" 
formulario cambio de password
"""
class PasswordChangingForm(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password1 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))
    new_password2 = forms.CharField(max_length=100, widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta:
        model = User
        fields = ('old_password', 'new_password1', 'new_password2')

sitio/main/views.py
from email import message
from msilib.schema import ListView
from re import template
#from django.shortcuts import render
from django.views import generic
#from django.views import View
from main.forms import BlogForm
from .models import (
    Blog)


class IndexView(generic.TemplateView):
	template_name = "main/index.html"
	
	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		#userprofiles = UserProfile.objects.filter(is_active=True)
		#testimonials = Testimonial.objects.filter(is_active=True)
		#certificates = Certificate.objects.filter(is_active=True)
		blogs = Blog.objects.filter(is_active=True)
		#portfolio = Portfolio.objects.filter(is_active=True)
	
		#context["userprofiles"] = userprofiles
		#context["testimonials"] = testimonials
		#context["certificates"] = certificates
		context["blogs"] = blogs
		#context["portfolio"] = portfolio
		return context
class BlogAddInfo(generic.FormView):
	template_name= "main/blogaddinfo.html"
	form_class = BlogForm
	success_url = "main/blog.html"
"""
	def form_valid(self, form): 
		form.save()
		message.success(self.request,'Gracias por aportar en la página')
		return super().form_valid(form)
"""

class BlogView(generic.ListView):
	model = Blog
	template_name = "main/blog.html"
	paginate_by = 10
	
	def get_queryset(self):
		return super().get_queryset().filter(is_active=True)


class BlogDetailView(generic.DetailView):
	model = Blog
	template_name = "main/blog-detail.html"

sitio/miembros/views.py
from django.shortcuts import render
from django .views import generic
from django.urls import reverse_lazy
from .forms import SignUpForm, EditForm, PasswordChangingForm
from django.contrib.auth.views import PasswordChangeView

class UserRegister(generic.CreateView):
    form_class = SignUpForm
    template_name = 'registration/register.html'
    success_url = reverse_lazy('login')

class UserEdit(generic.UpdateView):
    form_class = EditForm
    template_name = 'registration/edit_profile.html'
    success_url = reverse_lazy('/')

    def get_object(self):
        return self.request.user

class PasswordsChange(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('password_success')

def password_success(request):
        return render(request, 'registration/password_success.html', {})

sitio/main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}{%endblock %}</title>
    <meta name="author" content="Did Coding Limited & James Granger Design">
    <link rel="canonical" href="{{request.path}}"/>
    <link rel="home" href="{% url 'main:home' %}"/>
    <meta name="description" content="{% block description %}{% endblock %}">
    <meta name="keywords" content="{% block keywords %}{% endblock %}">

    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/icon.jpg' %}">
    <link rel="apple-touch-icon" type="image/jpg" href="{% static 'images/icon.jpg' %}">

    <!-- ================================
    Start CSS
    ================================= -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.css">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% block extend_header%}{%endblock%}
    <!-- ================================
    End CSS
    ================================= -->

  </head>
  <body>
    {% include 'main/partials/messages.html' %}
    {% include 'main/partials/nav.html' %}

    {% block content %}
    {% endblock %}

    {% include 'main/partials/footer.html' %}

    <!-- ================================
    Start Scripts
    ================================= -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="https://unpkg.com/swiper@7.0.5/swiper-bundle.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
    {% block extend_footer %}{%endblock%}
    <!-- ================================
    End Scripts
    ================================= -->
  </body>
</html>

sitio/main/templates/main/blog-detail.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">{{object.name|title}}</h1>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto">
          <div class="authorCol">
            <h4 class="smTitle pb-3">{{object.author|title}}</h4>
          </div>
        </div>
        <div class="col-md">
          <h4 class="smTitle pb-3">{{object.timestamp.date}}</h4>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="sectionSpaceSm">
    <div class="container">
      {{object.body|safe}}
    </div>
  </div>
</section>

{% endblock %}
<!-- ================================
End Content
================================= -->
   

sitio/main/templates/main/blog.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section>
  <div class="innerPageBannerCol">
    <div class="container">
      <div class="row g-4 g-md-3  align-items-center">
        <div class="col-md-6">
          <div class="bannerContent">
            <h1 class="xlTitle pb-md-3">See our recent blogs below</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="lightBg">
    <div class="container">
      <div class="portfolioContentMain">
        <div class="row g-3 g-md-4 g-lg-5 portfolioRow">
          {% for obj in object_list %}
          <div class="col-md-6 pColMain">
            <div class="pCol">
              <a href="{% url 'main:blog' slug=obj.slug %}" >
              <img src="{{obj.image.url}}" alt="..." class="pImg">
              </a>
            </div>
          </div>
          {% endfor %}

        </div>
      </div>
    </div>
  </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 
    

sitio/main/templates/main/blogaddinfo.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<section><br><br><br><br><br><br><br></section>
<section>
    <div></div>
    <div class="ligthBg">
        <div class=container>
            <form id="BlogForm" method="POST" action "{% url 'main:blogaddinfo' %}" enctype="multipart/form-data" >
                {% csrf_token %}
                <label for="author">Author</label>
                {{form.author}}
                <label for="name">Name</label>
                {{form.name}}
                <label for="description">Description</label>
                {{form.description}}
                <label for="body">Body</label>    
                {{form.body}}
                <label for="image">Image</label>
                {{form.image}}
                <br>
                <br>

                <input class="btn btnPrimary" type="submit" value="Submit">
            </form>
        </div>
    </div>
</section>
<!-- ================================
End Content
================================= -->
{%endblock%} 

sitio/main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}{% endblock %}
{% block decription %}{% endblock %}
{% block keywords %}{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
<style>
  body {
      font-family: "Roboto", sans-serif;
      font-size: 18px;
      background-color: #fdfdfd;
  }

  .head_text {
      color: white;
  }

  .card {
      box-shadow: 0 16px 48px #E3E7EB;
  }
</style>
<header class="masthead">
  <div class="overlay"></div>
  <div class="container">
      <div class="row">
          <div class=" col-md-8 col-md-10 mx-auto">
              <div class="site-heading">
                  <h3 class=" site-heading my-4 mt-3 text-white"> Bienvenido a Nuestro Blog de nuestros Mangas </h3>
                  <p class="text-light">¡Nos encanta Publicar series, así como a ti leerlas! &nbsp
                  </p>
              </div>
          </div>
      </div>
  </div>
</header>
<section>
  <div class="sectionSpaceSm lightBg">
    <div class="container">
      <div class="row pb-3">
        <div class="col">
          <h4 class="smText regular">Recent posts</h4>
        </div>
        <div class="col-auto">
          <a href="{% url 'main:blogs' %}" class="simpleLink">View all</a>
        </div>
      </div>
      <div class="row g-3">
      {% for b in blogs %}
      {% if b.is_active %}
        <div class="col-lg-6">
          <div class="cardStyle1">
            <h4 class="mdTitle cs1Title"><a href="{% url 'main:blog' slug=b.slug %}">{{b.name}}</a></h4>
            <ul class="cardOptionCol">
              <li>{{b.timestamp.date}}</li>
              <li>{{b.author}}</li>
            </ul>
            <p>{{b.description}}</p>
          </div>
        </div>
        {% endif %}
        {% endfor %}

      </div>
    </div>
  </div>
</section>
{% endblock %}
<!-- ================================
End Content
================================= -->

sitio/main/templates/main/partials/footer.html
{% load static %}
<!-- ================================
Start Footer
================================= -->
<footer>
    <div class="footerCol">
    <div class="container">
        <ul class="socialCol">
        <li><a href="https://about.me/jmastino23"><img src="{% static 'images/fb.svg' %}" alt="..."></a></li>
        <li><a href="https://about.me/jmastino23"><img src="{% static 'images/insta.svg' %}" alt="..."></a></li>
        <li><a href="https://about.me/jmastino23"><img src="{% static 'images/twitter.svg' %}" alt="..."></a></li>
        <li><a href="https://about.me/jmastino23"><img src="{% static 'images/linkedin.svg' %}" alt="..."></a></li>
        <li><a href="https://github.com/jmastino"><img src="{% static 'images/git.svg' %}" alt="..."></a></li>
        </ul>
        <div class="copyrightCol">
        <p>Copyright ©{% now 'Y' %} All rights reserved. Designed by <a href="javascript:void(0)" target="_blank">Shueshia</a></p>
        </div>
    </div>
    </div>
</footer>
<!-- ================================
End Footer
================================= -->

sitio/main/templates/main/partials/nav.html
{% load static %}
<!-- ================================
Start Navigation Bar
================================= -->
<header>
    <div class="headerCol">
    <div class="container-fluid">
        <div class="row align-items-center">
        <div class="col-auto">
            <div class="logoCol"><a href="{% url 'main:home' %}"><img src="{% static 'images/logo.png' %}" alt="..."></a></div>
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                </div>
            </div>
        </div>
        <div class="col">
            <div class="d-md-none">
            <button class="navToggle">
                <span class="navToggle__text">Toggle Menu</span>
            </button>
            </div>
            <div class="navCollapseCol">
            <div class="navCol">
                <ul>
                <li><a href="{%url 'main:home'%}">Home</a></li>            
                <li><a href="{% url 'main:blogs' %}">Blog</a></li>
                <li><a href="#">Sign In</a></li>
                <li><a href="{% url 'main:blogaddinfo' %}">Blog add</a></li>
                </ul>
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</header>
<!-- ================================
End Navigation Bar
================================= -->

sitio/main/templates/main/reviews.html
{% extends "base.html" %}
{% block content %}




{%endblock%}